---
# tasks file for centos7-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Debian 9. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - not ansible_distribution == "CentOS"
      - not ansible_distribution_release == "7"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include: prelim.yml
  become: true
  tags:
      - prelim_tasks
      - always

- include: section1.yml
  become: true
  when: centos7cis_section_1
  tags: section1

- include: section2.yml
  become: true
  when: centos7cis_section_2
  tags: section2

- include: section3.yml
  become: true
  when: centos7cis_section_3
  tags: section3

- include: section4.yml
  become: true
  when: centos7cis_section_4
  tags: section4

- include: section5.yml
  become: true
  when: centos7cis_section_5
  tags: section5

- include: section6.yml
  become: true
  when: centos7cis_section_6
  tags: section6